baseurl = "/"
languageCode = "en-us"
title = "秋 宁"
theme = "anatole"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
summarylength = 10
enableEmoji = true
# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"


[permalinks]
   post = "/:year/:month/:day/:slug/"
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "Blog"
  url = "/post/"

  [[menu.main]]
  name = "Notebook"
  weight = 300
  identifier = "notebook"
  url = "/notebook/"
  
  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

[params]
    title = "Hi，我是秋宁"
    author = "Juan Liu"
    description = "总要记得 仰望星空"
    profilePicture = "images/logo.jpg"
    keywords = ""
    favicon = ""
    customCss = []
    mainSections = ["post"]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "images/logo.jpg"
    width = 50
    height = 50
    alt = "Logo"


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
#[[params.socialIcons]]
#icon = "fa-linkedin"
#title = "Linkedin"
#url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/Qiuning-Liu"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:fantasticjoanna@outlook.com"



