---
title: try
author: Qiuning
date: '2020-06-08'
slug: try
categories:
  - R
tags:
  - R Markdown
Description: ''
DisableComments: no
---

```{r, include=FALSE}
library(tidyverse)
library(echarts4r)
knitr::opts_chunk$set(collapse = T, warning = FALSE, message = FALSE, tidy = T,comment='~#',prompt=TRUE)
# remotes::install_git("https://gitee.com/JohnCoene/echarts4r") # gitee
```

```{r}
head(mtcars)
```

```{r}
mtcars[1:5,] %>% rownames_to_column(.,var = 'name') %>% 
  e_charts(name) %>%
  e_radar(drat, name = ' ',max = max(mtcars$drat)+1) %>%
  e_tooltip(trigger = "item") #鼠标悬停可看到item的坐标

```

```{r}
mtcars %>% 
  e_charts(qsec) %>%
  e_line(mpg)

points <- mtcars[1:3,]
mtcars %>% 
  e_charts_("qsec") %>%
  e_line(mpg) %>%
  e_data(points, qsec) %>%
  e_scatter(mpg, color = "blue")

```


```{r}
df <- data.frame(
  x = LETTERS[1:5],
  y = runif(5, 1, 5),
  z = runif(5, 3, 7)
)

df %>% 
  e_charts(x) %>%  
  e_radar(y, max = 7) %>% 
  e_radar(z) %>% 
  e_tooltip(trigger = "item")
```

```{r}
volcano %>%
as.table() %>%
as.data.frame() %>%
dplyr::mutate(
Var1 = as.integer(Var1),
Var2 = as.integer(Var2)
) %>%
e_charts(Var1) %>%
e_bar_3d(Var2, Freq) %>%
e_visual_map(Freq)

```

<!-- ```{r} -->
<!-- url <- paste0("https://ecomfe.github.io/echarts-examples/","public/data-gl/asset/data/population.json") -->
<!-- data <- jsonlite::fromJSON(url) -->
<!-- data <- as.data.frame(data) -->
<!-- names(data) <- c("lon", "lat", "value") -->

<!-- # globe -->
<!-- data %>% -->
<!-- e_charts(lon) %>% -->
<!-- e_globe() %>% -->
<!-- e_bar_3d(lat, value, coord_system = "globe") %>% -->
<!-- e_visual_map() -->

<!-- ``` -->

<!-- ```{r} -->

<!-- # get3d -->
<!-- data %>% -->
<!-- e_charts(lon) %>% -->
<!-- e_geo_3d() %>% -->
<!-- e_bar_3d(lat, value, coord_system = "geo3D") %>% -->
<!-- e_visual_map() -->
<!-- # stacked -->
<!-- v <- LETTERS[1:10] -->
<!-- matrix <- data.frame( -->
<!-- x = sample(v, 300, replace = TRUE), -->
<!-- y = sample(v, 300, replace = TRUE), -->
<!-- z1 = rnorm(300, 10, 1), -->
<!-- z2 = rnorm(300, 10, 1), -->
<!-- stringsAsFactors = FALSE -->
<!-- ) %>% -->
<!-- dplyr::group_by(x, y) %>% -->
<!-- dplyr::summarise( -->
<!-- z1 = sum(z1), -->
<!-- z2 = sum(z2) -->
<!-- ) %>% -->
<!-- dplyr::ungroup() -->
<!-- trans <- list(opacity = 0.4) # transparency -->
<!-- emphasis <- list(itemStyle = list(color = "#313695")) -->
<!-- matrix %>% -->
<!-- e_charts(x) %>% -->
<!-- e_bar_3d(y, z1, stack = "stack", name = "Serie 1", itemStyle = trans, emphasis = emphasis) %>% -->
<!-- e_bar_3d(y, z2, stack = "stack", name = "Serie 2", itemStyle = trans, emphasis = emphasis) %>% -->
<!-- e_legend() -->
<!-- # timeline -->
<!-- matrix %>% -->
<!-- group_by(x) %>% -->
<!-- e_charts(y, timeline = TRUE) %>% -->
<!-- e_bar_3d(z1, z2) %>% -->
<!-- e_visual_map(z2) -->


<!-- ``` -->



```{r}
v <- LETTERS[1:10]
matrix <- data.frame(
  x = sample(v, 300, replace = TRUE), 
  y = sample(v, 300, replace = TRUE), 
  z1 = rnorm(300, 10, 1),
  z2 = rnorm(300, 10, 1),
  stringsAsFactors = FALSE
) %>% 
  dplyr::group_by(x, y) %>% 
  dplyr::summarise(
    z1 = sum(z1),
    z2 = sum(z2)
  ) %>% 
  dplyr::ungroup() 
  
trans <- list(opacity = 0.4) # transparency
emphasis <- list(itemStyle = list(color = "#313695"))
  
matrix %>% 
  e_charts(x) %>% 
  e_bar_3d(y, z1, stack = "stack", name = "Serie 1", itemStyle = trans, emphasis = emphasis) %>%
  e_bar_3d(y, z2, stack = "stack", name = "Serie 2", itemStyle = trans, emphasis = emphasis) %>% 
  e_legend()
```















